spring:
  application:
    name: eureka-server
  cloud:
    config:
      uri: http://localhost:8071
  config:
    import: optional:configserver:http://localhost:8071
ribbon:
  eureka:
    enabled: false
